[package]
name = "firn"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "core",
    "desktop",
    "arch/x86",
]

[dependencies]
firn_core = { path = "core" }
firn_arch_x86 = { path = "arch/x86", optional = true }

[features]
arch_x86 = ["firn_arch_x86"]
