[package]
name = "firn-arch-x86-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.90", features = ["full"] }
quote = "1.0.17"
proc-macro2 = "1.0.36"
strum = "0.24.0"
strum_macros = "0.24.0"
