[package]
name = "firn-arch-x86"
version = "0.1.0"
edition = "2021"

[dependencies]
firn-core = { path = "../../core" }
firn-arch-x86-macros = { path = "macros" }

num-traits = "0.2.14"
num-derive = "0.3.3"
chrono = "0.4.19"
